DROP TABLE "MAINPRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "USERINFO" CASCADE CONSTRAINTS;
DROP TABLE "CART" CASCADE CONSTRAINTS;
DROP TABLE "SUBPRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "ORDERINFO" CASCADE CONSTRAINTS;
DROP TABLE "BOARD" CASCADE CONSTRAINTS;
DROP TABLE "PRODUCTLIST" CASCADE CONSTRAINTS;
DROP TABLE "REFUND" CASCADE CONSTRAINTS;
DROP TABLE "RECENT" CASCADE CONSTRAINTS;

DROP sequence "BOARD_SEQ";
DROP sequence "CART_SEQ";
DROP sequence "ORDERINFO_SEQ";
DROP sequence "PRODUCTLIST_SEQ";
DROP sequence "RECENT_SEQ";
DROP sequence "REFUND_SEQ";
DROP sequence "USERINFO_SEQ";